# Generated by Django 5.0.6 on 2024-11-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField()),
                ('domain', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('predicted_proficiency', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('predicted_average_score', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
